default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: h4rdc0r3
  host: localhost

development:
  <<: *default
  database: savemydemand_development

test:
  <<: *default
  database: savemydemand_test